AVAILABILITY_QUERY = """<soap:Envelope 
    xmlns:soap="http://www.w3.org/2003/05/soap-envelope"
    xmlns:wss="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
    xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
	xmlns:sec="http://xml.amadeus.com/2010/06/Security_v1" 
	xmlns:typ="http://xml.amadeus.com/2010/06/Types_v1" 
	xmlns:iat="http://www.iata.org/IATA/2007/00/IATA2010.1" 
	xmlns:app="http://xml.amadeus.com/2010/06/AppMdw_CommonTypes_v3" 
	xmlns:link="http://wsdl.amadeus.com/2010/06/ws/Link_v1" 
	xmlns:ses="http://xml.amadeus.com/2010/06/Session_v3">

   <soapenv:Header xmlns:add="http://www.w3.org/2005/08/addressing">
      <add:MessageID>WbsConsu-{MESSAGE_ID}</add:MessageID>
      <add:Action>http://webservices.amadeus.com/FMPTBQ_23_1_1A</add:Action>
      <add:To>https://nodeD1.test.webservices.amadeus.com/1ASIWCARCPJ</add:To>
      <oas:Security xmlns:oas="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
					xmlns:oas1="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
         <oas:UsernameToken oas1:Id="UsernameToken-1">
			<oas:Username>{USERNAME}</oas:Username>
            <oas:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">
				{NONCE}
			</oas:Nonce>
            <oas:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">
				{PASSWORD_DIGEST}
			</oas:Password>
            <oas1:Created>{CREATED_AT}</oas1:Created>
		</oas:UsernameToken>
	  </oas:Security>
      <AMA_SecurityHostedUser xmlns="http://xml.amadeus.com/2010/06/Security_v1">
         <UserID AgentDutyCode="SU" RequestorType="U" PseudoCityCode="KIN1S2312" POS_Type="1"/>
      </AMA_SecurityHostedUser>
      <awsse:Session TransactionStatusCode="Start"
         xmlns:awsse="http://xml.amadeus.com/2010/06/Session_v3"/>
    </soapenv:Header>

   <soapenv:Body>
      <Fare_MasterPricerTravelBoardSearch>
         <numberOfUnit>
            <unitNumberDetail>
               <numberOfUnits>2</numberOfUnits>
               <typeOfUnit>PX</typeOfUnit>
            </unitNumberDetail>
            <unitNumberDetail>
               <numberOfUnits>100</numberOfUnits>
               <typeOfUnit>RC</typeOfUnit>
            </unitNumberDetail>
         </numberOfUnit>
         <paxReference>
            <ptc>ADT</ptc>
            <traveller>
               <ref>1</ref>
            </traveller>
            <traveller>
               <ref>2</ref>
            </traveller>
         </paxReference>
         <fareOptions>
            <pricingTickInfo>
               <pricingTicketing>
                  <priceType>ET</priceType>
                  <priceType>RP</priceType>
                  <priceType>RU</priceType>
                  <priceType>TAC</priceType>
                  <priceType>XND</priceType>
                  <priceType>XLA</priceType>
                  <priceType>XLO</priceType>
                  <priceType>XLC</priceType>
                  <priceType>XND</priceType>
               </pricingTicketing>
            </pricingTickInfo>
         </fareOptions>
         <travelFlightInfo>
            <companyIdentity>
               <carrierQualifier>X</carrierQualifier>
               <carrierId>NK</carrierId>
               <carrierId>F9</carrierId>
            </companyIdentity>
            <flightDetail>
               <flightType>N</flightType>
            </flightDetail>
         </travelFlightInfo>
         <itinerary>
            <requestedSegmentRef>
               <segRef>1</segRef>
            </requestedSegmentRef>
            <departureLocalization>
               <departurePoint>
                  <locationId>HAV</locationId>
               </departurePoint>
            </departureLocalization>
            <arrivalLocalization>
               <arrivalPointDetails>
                  <locationId>SCU</locationId>
               </arrivalPointDetails>
            </arrivalLocalization>
            <timeDetails>
               <firstDateTimeDetail>
                  <date>300825</date>
               </firstDateTimeDetail>
            </timeDetails>
         </itinerary>
         <itinerary>
            <requestedSegmentRef>
               <segRef>2</segRef>
            </requestedSegmentRef>
            <departureLocalization>
               <departurePoint>
                  <locationId>SCU</locationId>
               </departurePoint>
            </departureLocalization>
            <arrivalLocalization>
               <arrivalPointDetails>
                  <locationId>HAV</locationId>
               </arrivalPointDetails>
            </arrivalLocalization>
            <timeDetails>
               <firstDateTimeDetail>
                  <date>040925</date>
               </firstDateTimeDetail>
            </timeDetails>
         </itinerary>
      </Fare_MasterPricerTravelBoardSearch>
   </soapenv:Body>
</soap:Envelope>"""
